blank_issues_enabled: false
contact_links:
  - name: Email Support
    url: mailto:support@fronsky.nl
    about: Contact us directly via email for support or questions.
  - name: Website
    url: https://fronsky.nl/projects/prefix
    about: Visit the official Prefix website for downloads and information.

